name: Apache Kafka2
description: |
  Kafka maneger
version: 1.0.0-rancher1
category: Clustering
maintainer: ""
minimum_rancher_version: v0.59.0
license:
projectURL: https://github.com/yahoo/kafka-manager
